# Generated by Django 4.1.7 on 2023-04-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
