# Generated by Django 4.1.7 on 2023-04-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
